#!/bin/sh /etc/rc.common

START=80
NAME=fzu-network
EXTRA_COMMANDS="status"
EXTRA_HELP="        status          Service status"

NE_TIPS='网络认证服务已停止'

restart() {
	start
}

uci_get_by_name() {
	local ret=$(uci get $NAME.$1.$2 2>/dev/null)
	printf '%s\n' "${ret:-$3}"
}

uci_bool_by_name() {
	case "$(uci_get_by_name $1 $2)" in
		1|on|true|yes|enabled) return 0;;
	esac
	return 1
}

add_hotplug() {
	cat <<EOF > "/etc/hotplug.d/iface/${START}-${NAME}"
#!/bin/sh /etc/rc.common

[ "Z\$ACTION" = "Zifup" -a "Z\$INTERFACE" = "Zwan" ] || exit 0

DATE=\$(date +'%Y-%m-%d %H:%M:%S')
( sleep 10 && ( echo "\$DATE IFUP-WAN" && /usr/sbin/fzu-network ) >> /var/log/fzu-network.log 2>&1 ) &

exit 0
EOF
	chmod +x "/etc/hotplug.d/iface/${START}-${NAME}"
}

start() {
	$(uci_bool_by_name base enable) || {
		stop
		return 0
	}

	add_hotplug

	sed -i "/${NE_TIPS}/d" /var/log/fzu-network.log

	local cron_expr=$(uci_get_by_name base time "*/5 * * * *")

	[ -f /etc/crontabs/root ] || mkdir -p /etc/crontabs && touch /etc/crontabs/root
	sed -i '/fzu-network/d' /etc/crontabs/root
	echo "$cron_expr /usr/sbin/fzu-network >> /var/log/fzu-network.log 2>&1" >> /etc/crontabs/root
	if [ "$(/etc/init.d/cron status)" = "running" ]; then
		/etc/init.d/cron reload
	fi

	( /usr/sbin/fzu-network >> /var/log/fzu-network.log 2>&1 ) &
}

stop() {
	rm -rf "/etc/hotplug.d/iface/${START}-${NAME}"
	sed -i '/fzu-network/d' /etc/crontabs/root >/dev/null 2>&1
	if [ "$(/etc/init.d/cron status)" = "running" ]; then
		/etc/init.d/cron reload
	fi
	echo "${NE_TIPS}" > /var/log/fzu-network.log
}

status() {
	if [ "$(/etc/init.d/cron status)" != "running" ]; then
		echo "inactive" && false
	else
		grep -q fzu-network /etc/crontabs/root && echo "running" || echo "inactive" && false
	fi
}
